# analysis_options.yaml
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Documentation related rules
    public_member_api_docs: true
    package_api_docs: true
    comment_references: true
    prefer_single_quotes: true
    avoid_print: true
    always_specify_types: false  # This can make code more readable
    prefer_relative_imports: true
    sort_constructors_first: true

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_return: error
    missing_required_param: error
    invalid_annotation_target: ignore
  exclude:
    - "lib/generated/**"
    - "test/**"